# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(db_index=True, max_length=8)),
                ('corpweixinid', models.CharField(db_index=True, max_length=10)),
                ('superiorid', models.CharField(db_index=True, default='', max_length=10)),
                ('assessors', models.TextField()),
                ('state', models.SmallIntegerField(choices=[(0, '\u65b0\u5efa'), (1, '\u5f85\u5ba1\u6838'), (2, '\u5f85\u8003\u6838'), (3, '\u8003\u6838\u5b8c\u6210')], default=0)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(db_index=True, max_length=8)),
                ('corpweixinid', models.CharField(max_length=10)),
                ('name', models.CharField(default='', max_length=20)),
                ('assessorid', models.CharField(db_index=True, max_length=10)),
                ('rawsocre', models.FloatField(default=0)),
                ('scorekeepin', models.BooleanField(default=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationBak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(db_index=True, max_length=8)),
                ('corpweixinid', models.CharField(max_length=10)),
                ('name', models.CharField(default='', max_length=20)),
                ('assessorid', models.CharField(db_index=True, default='', max_length=10)),
                ('rawsocre', models.FloatField(default=0)),
                ('scorekeepin', models.BooleanField(default=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(db_index=True, max_length=8)),
                ('corpweixinid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('socre', models.FloatField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TCorpWeixinToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstoken', models.CharField(max_length=600)),
                ('expiresdatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpweixinid', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('isleader', models.BooleanField(default=False)),
                ('superiorid', models.CharField(default='', max_length=10)),
                ('superiorname', models.CharField(default='', max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=1)),
                ('avatar', models.CharField(max_length=256)),
                ('enable', models.BooleanField(default=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='YearScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=4)),
                ('corpweixinid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('socre', models.FloatField()),
                ('level', models.CharField(choices=[('A', '\u7b49\u7ea7A'), ('B', '\u7b49\u7ea7B'), ('C', '\u7b49\u7ea7C'), ('D', '\u7b49\u7ea7D')], max_length=1)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='yearscore',
            unique_together=set([('year', 'corpweixinid')]),
        ),
        migrations.AlterUniqueTogether(
            name='quarterscore',
            unique_together=set([('quarter', 'corpweixinid')]),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationbak',
            unique_together=set([('quarter', 'corpweixinid')]),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together=set([('quarter', 'corpweixinid')]),
        ),
        migrations.AlterUniqueTogether(
            name='beevaluation',
            unique_together=set([('quarter', 'corpweixinid')]),
        ),
    ]
