# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beevaluation',
            name='quarter',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='beevaluation',
            name='superiorid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='quarter',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='evaluationbak',
            name='assessorid',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluationbak',
            name='quarter',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='quarterscore',
            name='quarter',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='yearscore',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
