# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20170322_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='socre',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scoreproportion',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='scorekeepin',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
