# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20170323_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationbak',
            name='socre',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationbak',
            name='scorekeepin',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationbak',
            unique_together=set([('quarter', 'corpweixinid', 'assessorid')]),
        ),
    ]
