# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20170323_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='beevaluation',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='beevaluation',
            name='superiorid',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
    ]
